# Conexion a MongoDB en AWS EC2:
spring.mongodb.host=44.211.11.219
spring.mongodb.port=27017
spring.mongodb.database=theca_db
spring.mongodb.authentication-database=admin
spring.mongodb.username=theca_user
spring.mongodb.password=theca_123

# Puerto del servidor:
server.port=8080

# Configuracion de JWT:
theca.app.jwtSecret=d2FwSnR5R2hhbUZ0eUdoYW1GdHlHaGFtRnR5R2hhbUZ0eUdoYW1GdHlHaGFtRnR5R2hhbUZ0eUdoYW1GdHlHaGFt
theca.app.jwtExpirationMs=86400000

# Configuracion de logging:
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR